### ISSUE TITLE
The file "horse.jpg" is not present at the initialization Projects / SVD / Load Image

### ISSUE THREAD

**Issue by edutools-service** [jetbrains-academy/Python-Libraries-NumPy#68]
The file "horse.jpg", which is needed to complete the task, is not present in directoy \Projects\SVD\task. 
PyDev console: starting.
Python 3.9.0 (tags/v3.9.0:9cf6752, Oct  5 2020, 15:34:40) [MSC v.1927 64 bit (AMD64)] on win32
runfile('C:\\Users\\knasi\\OneDrive - UAB\\Python\\Python Libraries - NumPy1\\Projects\\SVD\\task\\task.py', wdir='C:\\Users\\knasi\\OneDrive - UAB\\Python\\Python Libraries - NumPy1\\Projects\\SVD\\task')
Traceback (most recent call last):
  File "C:\Users\knasi\AppData\Local\JetBrains\Toolbox\apps\PyCharm-P\ch-0\231.9161.41\plugins\python\helpers\pydev\pydevconsole.py", line 364, in runcode
    coro = func()
  File "<input>", line 1, in <module>
  File "C:\Users\knasi\AppData\Local\JetBrains\Toolbox\apps\PyCharm-P\ch-0\231.9161.41\plugins\python\helpers\pydev\_pydev_bundle\pydev_umd.py", line 198, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "C:\Users\knasi\AppData\Local\JetBrains\Toolbox\apps\PyCharm-P\ch-0\231.9161.41\plugins\python\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "C:\Users\knasi\OneDrive - UAB\Python\Python Libraries - NumPy1\Projects\SVD\task\task.py", line 3, in <module>
    img = plt.imread('horse.jpg')  # Read image and transform it into a NumPy array.
  File "C:\Users\knasi\OneDrive - UAB\Python\Python Libraries - NumPy1\.idea\VirtualEnvironment\lib\site-packages\matplotlib\pyplot.py", line 2195, in imread
    return matplotlib.image.imread(fname, format)
  File "C:\Users\knasi\OneDrive - UAB\Python\Python Libraries - NumPy1\.idea\VirtualEnvironment\lib\site-packages\matplotlib\image.py", line 1563, in imread
    with img_open(fname) as image:
  File "C:\Users\knasi\OneDrive - UAB\Python\Python Libraries - NumPy1\.idea\VirtualEnvironment\lib\site-packages\PIL\Image.py", line 3236, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: 'horse.jpg'

**Comment by DaniilBogdanovJB** [comment]
Hello,
The issue was reproduced; here is a YouTrack ticket: https://youtrack.jetbrains.com/issue/EDC-892/Python-Libraries-NumPy-Projects-SVD-Issues-with-horse.jpg

**Comment by kochaika** [comment]
Fixed starting from the `2024.8-2024.2-679` version of JetBrains Academy plugin
