### ISSUE TITLE
somedata.csv is encoding badly  Array Basics / Reading and Writing Files

### ISSUE THREAD

**Issue by edutools-service** [jetbrains-academy/Python-Libraries-NumPy#70]
HINT1, HINT2, CHECK failed to launch.
Traceback (most recent call last):
  File "C:\Users\rober\Python Libraries - NumPy\NumPy\Array Basics\Reading and Writing Files\task.py", line 19, in <module>
    arr = np.genfromtxt(data,delimiter=',',skip_footer=3 )
  File "C:\Users\rober\Python Libraries - NumPy\.idea\VirtualEnvironment\lib\site-packages\numpy\lib\npyio.py", line 2009, in genfromtxt
    first_line = _decode_line(next(fhd), encoding)
  File "C:\Users\rober\AppData\Local\Programs\Python\Python39\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x8d in position 145: character maps to <undefined>

**Comment by DaniilBogdanovJB** [comment]
Similar to https://github.com/jetbrains-academy/Python-Libraries-NumPy/issues/67, possibly a duplicate.
Needs some clarifications on how to reproduce the issue.
